/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityEntry {
  'at' : Timestamp,
  'lessonId' : LessonId,
  'kind' : string,
  'detail' : string,
}
export interface AiExplanation {
  'question' : string,
  'answer' : string,
  'level' : string,
}
export interface AnswerResult {
  'correctIndex' : bigint,
  'explanation' : string,
  'correct' : boolean,
}
export interface Badge {
  'id' : BadgeId,
  'icon' : string,
  'name' : string,
  'description' : string,
}
export type BadgeId = string;
export interface Cell { 'value' : Value, 'name' : string }
export interface CondensedPath {
  'lessonId' : LessonId,
  'summary' : string,
  'steps' : Array<LearningStep>,
  'durationMinutes' : DurationMinutes,
}
export type DurationMinutes = bigint;
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface ExamAnswer {
  'exerciseId' : ExerciseId,
  'selectedIndex' : bigint,
}
export type ExamId = bigint;
export interface ExamQuestion {
  'exerciseId' : ExerciseId,
  'prompt' : string,
  'choices' : Array<string>,
}
export interface ExamQuestionResult {
  'exerciseId' : ExerciseId,
  'correctIndex' : bigint,
  'explanation' : string,
  'correct' : boolean,
  'selectedIndex' : bigint,
  'prompt' : string,
}
export interface ExamResult {
  'total' : bigint,
  'results' : Array<ExamQuestionResult>,
  'score' : bigint,
  'examId' : ExamId,
  'sessionId' : SessionId,
}
export interface ExamSession {
  'lessonId' : LessonId,
  'startedAt' : Timestamp,
  'submitted' : boolean,
  'durationSeconds' : bigint,
  'examId' : ExamId,
  'sessionId' : SessionId,
}
export interface ExamView {
  'id' : ExamId,
  'lessonId' : LessonId,
  'title' : string,
  'durationSeconds' : bigint,
  'questions' : Array<ExamQuestion>,
}
export type ExerciseId = bigint;
export interface ExerciseView {
  'id' : ExerciseId,
  'lessonId' : LessonId,
  'prompt' : string,
  'choices' : Array<string>,
}
export type LearningStep = { 'entrainer' : null } |
  { 'memoriser' : null } |
  { 'comprendre' : null } |
  { 'corriger' : null } |
  { 'exemple' : null } |
  { 'tester' : null } |
  { 'maitriser' : null };
export interface LessonDetail {
  'id' : LessonId,
  'curriculum' : string,
  'title' : string,
  'country' : string,
  'explanation' : string,
  'level' : string,
  'language' : string,
  'memorizationSummary' : string,
  'example' : string,
  'keyPoints' : Array<string>,
  'subjectId' : SubjectId,
  'memorizationPoints' : Array<string>,
}
export type LessonId = bigint;
export interface LessonProgress {
  'lessonId' : LessonId,
  'masteryRate' : bigint,
  'updatedAt' : Timestamp,
  'steps' : Array<StepState>,
  'currentStep' : LearningStep,
}
export interface LessonSummary {
  'id' : LessonId,
  'title' : string,
  'level' : string,
  'subjectId' : SubjectId,
}
export interface ProfileInput {
  'curriculum' : string,
  'country' : string,
  'level' : string,
  'language' : string,
}
export interface ProfileView {
  'curriculum' : string,
  'studentLevel' : bigint,
  'country' : string,
  'exercisesCompleted' : bigint,
  'level' : string,
  'language' : string,
  'updatedAt' : Timestamp,
  'lessonsCompleted' : bigint,
  'points' : bigint,
}
export interface ProgressOverview {
  'subjects' : Array<SubjectMastery>,
  'recentActivity' : Array<ActivityEntry>,
  'level' : bigint,
  'totalPoints' : bigint,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface RevisionItem {
  'lessonId' : LessonId,
  'title' : string,
  'subjectId' : SubjectId,
  'priority' : bigint,
  'reason' : string,
}
export interface RewardState {
  'badges' : Array<Badge>,
  'level' : bigint,
  'points' : bigint,
}
export type SessionId = bigint;
export interface StepState { 'step' : LearningStep, 'completed' : boolean }
export type SubjectId = bigint;
export interface SubjectMastery {
  'masteryRate' : bigint,
  'name' : string,
  'subjectId' : SubjectId,
}
export interface SubjectView {
  'id' : SubjectId,
  'icon' : string,
  'name' : string,
  'description' : string,
}
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'advanceStep' : ActorMethod<[bigint], LessonProgress>,
  'askAiTeacher' : ActorMethod<[bigint, string], AiExplanation>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'execute' : ActorMethod<[string], Result>,
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCondensedPath' : ActorMethod<[bigint, bigint], CondensedPath>,
  'getExam' : ActorMethod<[bigint], [] | [ExamView]>,
  'getLesson' : ActorMethod<[bigint], [] | [LessonDetail]>,
  'getLessonProgress' : ActorMethod<[bigint], [] | [LessonProgress]>,
  'getProfile' : ActorMethod<[], [] | [ProfileView]>,
  'getProgress' : ActorMethod<[], ProgressOverview>,
  'getRewards' : ActorMethod<[], RewardState>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listExercises' : ActorMethod<[bigint], Array<ExerciseView>>,
  'listLessons' : ActorMethod<[bigint, string], Array<LessonSummary>>,
  'listRevisions' : ActorMethod<[], Array<RevisionItem>>,
  'listSubjects' : ActorMethod<[], Array<SubjectView>>,
  'schema' : ActorMethod<[], string>,
  'startExam' : ActorMethod<[bigint], ExamSession>,
  'submitAnswer' : ActorMethod<[bigint, bigint], AnswerResult>,
  'submitExam' : ActorMethod<[bigint, Array<ExamAnswer>], ExamResult>,
  'updateProfile' : ActorMethod<[ProfileInput], ProfileView>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];