/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const LessonId = IDL.Nat;
export const Timestamp = IDL.Int;
export const LearningStep = IDL.Variant({
  'entrainer' : IDL.Null,
  'memoriser' : IDL.Null,
  'comprendre' : IDL.Null,
  'corriger' : IDL.Null,
  'exemple' : IDL.Null,
  'tester' : IDL.Null,
  'maitriser' : IDL.Null,
});
export const StepState = IDL.Record({
  'step' : LearningStep,
  'completed' : IDL.Bool,
});
export const LessonProgress = IDL.Record({
  'lessonId' : LessonId,
  'masteryRate' : IDL.Nat,
  'updatedAt' : Timestamp,
  'steps' : IDL.Vec(StepState),
  'currentStep' : LearningStep,
});
export const AiExplanation = IDL.Record({
  'question' : IDL.Text,
  'answer' : IDL.Text,
  'level' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const DurationMinutes = IDL.Nat;
export const CondensedPath = IDL.Record({
  'lessonId' : LessonId,
  'summary' : IDL.Text,
  'steps' : IDL.Vec(LearningStep),
  'durationMinutes' : DurationMinutes,
});
export const ExamId = IDL.Nat;
export const ExerciseId = IDL.Nat;
export const ExamQuestion = IDL.Record({
  'exerciseId' : ExerciseId,
  'prompt' : IDL.Text,
  'choices' : IDL.Vec(IDL.Text),
});
export const ExamView = IDL.Record({
  'id' : ExamId,
  'lessonId' : LessonId,
  'title' : IDL.Text,
  'durationSeconds' : IDL.Nat,
  'questions' : IDL.Vec(ExamQuestion),
});
export const SubjectId = IDL.Nat;
export const LessonDetail = IDL.Record({
  'id' : LessonId,
  'curriculum' : IDL.Text,
  'title' : IDL.Text,
  'country' : IDL.Text,
  'explanation' : IDL.Text,
  'level' : IDL.Text,
  'language' : IDL.Text,
  'memorizationSummary' : IDL.Text,
  'example' : IDL.Text,
  'keyPoints' : IDL.Vec(IDL.Text),
  'subjectId' : SubjectId,
  'memorizationPoints' : IDL.Vec(IDL.Text),
});
export const ProfileView = IDL.Record({
  'curriculum' : IDL.Text,
  'studentLevel' : IDL.Nat,
  'country' : IDL.Text,
  'exercisesCompleted' : IDL.Nat,
  'level' : IDL.Text,
  'language' : IDL.Text,
  'updatedAt' : Timestamp,
  'lessonsCompleted' : IDL.Nat,
  'points' : IDL.Nat,
});
export const SubjectMastery = IDL.Record({
  'masteryRate' : IDL.Nat,
  'name' : IDL.Text,
  'subjectId' : SubjectId,
});
export const ActivityEntry = IDL.Record({
  'at' : Timestamp,
  'lessonId' : LessonId,
  'kind' : IDL.Text,
  'detail' : IDL.Text,
});
export const ProgressOverview = IDL.Record({
  'subjects' : IDL.Vec(SubjectMastery),
  'recentActivity' : IDL.Vec(ActivityEntry),
  'level' : IDL.Nat,
  'totalPoints' : IDL.Nat,
});
export const BadgeId = IDL.Text;
export const Badge = IDL.Record({
  'id' : BadgeId,
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const RewardState = IDL.Record({
  'badges' : IDL.Vec(Badge),
  'level' : IDL.Nat,
  'points' : IDL.Nat,
});
export const ExerciseView = IDL.Record({
  'id' : ExerciseId,
  'lessonId' : LessonId,
  'prompt' : IDL.Text,
  'choices' : IDL.Vec(IDL.Text),
});
export const LessonSummary = IDL.Record({
  'id' : LessonId,
  'title' : IDL.Text,
  'level' : IDL.Text,
  'subjectId' : SubjectId,
});
export const RevisionItem = IDL.Record({
  'lessonId' : LessonId,
  'title' : IDL.Text,
  'subjectId' : SubjectId,
  'priority' : IDL.Nat,
  'reason' : IDL.Text,
});
export const SubjectView = IDL.Record({
  'id' : SubjectId,
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const SessionId = IDL.Nat;
export const ExamSession = IDL.Record({
  'lessonId' : LessonId,
  'startedAt' : Timestamp,
  'submitted' : IDL.Bool,
  'durationSeconds' : IDL.Nat,
  'examId' : ExamId,
  'sessionId' : SessionId,
});
export const AnswerResult = IDL.Record({
  'correctIndex' : IDL.Nat,
  'explanation' : IDL.Text,
  'correct' : IDL.Bool,
});
export const ExamAnswer = IDL.Record({
  'exerciseId' : ExerciseId,
  'selectedIndex' : IDL.Nat,
});
export const ExamQuestionResult = IDL.Record({
  'exerciseId' : ExerciseId,
  'correctIndex' : IDL.Nat,
  'explanation' : IDL.Text,
  'correct' : IDL.Bool,
  'selectedIndex' : IDL.Nat,
  'prompt' : IDL.Text,
});
export const ExamResult = IDL.Record({
  'total' : IDL.Nat,
  'results' : IDL.Vec(ExamQuestionResult),
  'score' : IDL.Nat,
  'examId' : ExamId,
  'sessionId' : SessionId,
});
export const ProfileInput = IDL.Record({
  'curriculum' : IDL.Text,
  'country' : IDL.Text,
  'level' : IDL.Text,
  'language' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'advanceStep' : IDL.Func([IDL.Nat], [LessonProgress], []),
  'askAiTeacher' : IDL.Func([IDL.Nat, IDL.Text], [AiExplanation], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCondensedPath' : IDL.Func([IDL.Nat, IDL.Nat], [CondensedPath], ['query']),
  'getExam' : IDL.Func([IDL.Nat], [IDL.Opt(ExamView)], ['query']),
  'getLesson' : IDL.Func([IDL.Nat], [IDL.Opt(LessonDetail)], ['query']),
  'getLessonProgress' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(LessonProgress)],
      ['query'],
    ),
  'getProfile' : IDL.Func([], [IDL.Opt(ProfileView)], ['query']),
  'getProgress' : IDL.Func([], [ProgressOverview], ['query']),
  'getRewards' : IDL.Func([], [RewardState], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listExercises' : IDL.Func([IDL.Nat], [IDL.Vec(ExerciseView)], ['query']),
  'listLessons' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Vec(LessonSummary)],
      ['query'],
    ),
  'listRevisions' : IDL.Func([], [IDL.Vec(RevisionItem)], ['query']),
  'listSubjects' : IDL.Func([], [IDL.Vec(SubjectView)], ['query']),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'startExam' : IDL.Func([IDL.Nat], [ExamSession], []),
  'submitAnswer' : IDL.Func([IDL.Nat, IDL.Nat], [AnswerResult], []),
  'submitExam' : IDL.Func([IDL.Nat, IDL.Vec(ExamAnswer)], [ExamResult], []),
  'updateProfile' : IDL.Func([ProfileInput], [ProfileView], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const LessonId = IDL.Nat;
  const Timestamp = IDL.Int;
  const LearningStep = IDL.Variant({
    'entrainer' : IDL.Null,
    'memoriser' : IDL.Null,
    'comprendre' : IDL.Null,
    'corriger' : IDL.Null,
    'exemple' : IDL.Null,
    'tester' : IDL.Null,
    'maitriser' : IDL.Null,
  });
  const StepState = IDL.Record({
    'step' : LearningStep,
    'completed' : IDL.Bool,
  });
  const LessonProgress = IDL.Record({
    'lessonId' : LessonId,
    'masteryRate' : IDL.Nat,
    'updatedAt' : Timestamp,
    'steps' : IDL.Vec(StepState),
    'currentStep' : LearningStep,
  });
  const AiExplanation = IDL.Record({
    'question' : IDL.Text,
    'answer' : IDL.Text,
    'level' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const DurationMinutes = IDL.Nat;
  const CondensedPath = IDL.Record({
    'lessonId' : LessonId,
    'summary' : IDL.Text,
    'steps' : IDL.Vec(LearningStep),
    'durationMinutes' : DurationMinutes,
  });
  const ExamId = IDL.Nat;
  const ExerciseId = IDL.Nat;
  const ExamQuestion = IDL.Record({
    'exerciseId' : ExerciseId,
    'prompt' : IDL.Text,
    'choices' : IDL.Vec(IDL.Text),
  });
  const ExamView = IDL.Record({
    'id' : ExamId,
    'lessonId' : LessonId,
    'title' : IDL.Text,
    'durationSeconds' : IDL.Nat,
    'questions' : IDL.Vec(ExamQuestion),
  });
  const SubjectId = IDL.Nat;
  const LessonDetail = IDL.Record({
    'id' : LessonId,
    'curriculum' : IDL.Text,
    'title' : IDL.Text,
    'country' : IDL.Text,
    'explanation' : IDL.Text,
    'level' : IDL.Text,
    'language' : IDL.Text,
    'memorizationSummary' : IDL.Text,
    'example' : IDL.Text,
    'keyPoints' : IDL.Vec(IDL.Text),
    'subjectId' : SubjectId,
    'memorizationPoints' : IDL.Vec(IDL.Text),
  });
  const ProfileView = IDL.Record({
    'curriculum' : IDL.Text,
    'studentLevel' : IDL.Nat,
    'country' : IDL.Text,
    'exercisesCompleted' : IDL.Nat,
    'level' : IDL.Text,
    'language' : IDL.Text,
    'updatedAt' : Timestamp,
    'lessonsCompleted' : IDL.Nat,
    'points' : IDL.Nat,
  });
  const SubjectMastery = IDL.Record({
    'masteryRate' : IDL.Nat,
    'name' : IDL.Text,
    'subjectId' : SubjectId,
  });
  const ActivityEntry = IDL.Record({
    'at' : Timestamp,
    'lessonId' : LessonId,
    'kind' : IDL.Text,
    'detail' : IDL.Text,
  });
  const ProgressOverview = IDL.Record({
    'subjects' : IDL.Vec(SubjectMastery),
    'recentActivity' : IDL.Vec(ActivityEntry),
    'level' : IDL.Nat,
    'totalPoints' : IDL.Nat,
  });
  const BadgeId = IDL.Text;
  const Badge = IDL.Record({
    'id' : BadgeId,
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const RewardState = IDL.Record({
    'badges' : IDL.Vec(Badge),
    'level' : IDL.Nat,
    'points' : IDL.Nat,
  });
  const ExerciseView = IDL.Record({
    'id' : ExerciseId,
    'lessonId' : LessonId,
    'prompt' : IDL.Text,
    'choices' : IDL.Vec(IDL.Text),
  });
  const LessonSummary = IDL.Record({
    'id' : LessonId,
    'title' : IDL.Text,
    'level' : IDL.Text,
    'subjectId' : SubjectId,
  });
  const RevisionItem = IDL.Record({
    'lessonId' : LessonId,
    'title' : IDL.Text,
    'subjectId' : SubjectId,
    'priority' : IDL.Nat,
    'reason' : IDL.Text,
  });
  const SubjectView = IDL.Record({
    'id' : SubjectId,
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const SessionId = IDL.Nat;
  const ExamSession = IDL.Record({
    'lessonId' : LessonId,
    'startedAt' : Timestamp,
    'submitted' : IDL.Bool,
    'durationSeconds' : IDL.Nat,
    'examId' : ExamId,
    'sessionId' : SessionId,
  });
  const AnswerResult = IDL.Record({
    'correctIndex' : IDL.Nat,
    'explanation' : IDL.Text,
    'correct' : IDL.Bool,
  });
  const ExamAnswer = IDL.Record({
    'exerciseId' : ExerciseId,
    'selectedIndex' : IDL.Nat,
  });
  const ExamQuestionResult = IDL.Record({
    'exerciseId' : ExerciseId,
    'correctIndex' : IDL.Nat,
    'explanation' : IDL.Text,
    'correct' : IDL.Bool,
    'selectedIndex' : IDL.Nat,
    'prompt' : IDL.Text,
  });
  const ExamResult = IDL.Record({
    'total' : IDL.Nat,
    'results' : IDL.Vec(ExamQuestionResult),
    'score' : IDL.Nat,
    'examId' : ExamId,
    'sessionId' : SessionId,
  });
  const ProfileInput = IDL.Record({
    'curriculum' : IDL.Text,
    'country' : IDL.Text,
    'level' : IDL.Text,
    'language' : IDL.Text,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'advanceStep' : IDL.Func([IDL.Nat], [LessonProgress], []),
    'askAiTeacher' : IDL.Func([IDL.Nat, IDL.Text], [AiExplanation], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCondensedPath' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [CondensedPath],
        ['query'],
      ),
    'getExam' : IDL.Func([IDL.Nat], [IDL.Opt(ExamView)], ['query']),
    'getLesson' : IDL.Func([IDL.Nat], [IDL.Opt(LessonDetail)], ['query']),
    'getLessonProgress' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(LessonProgress)],
        ['query'],
      ),
    'getProfile' : IDL.Func([], [IDL.Opt(ProfileView)], ['query']),
    'getProgress' : IDL.Func([], [ProgressOverview], ['query']),
    'getRewards' : IDL.Func([], [RewardState], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listExercises' : IDL.Func([IDL.Nat], [IDL.Vec(ExerciseView)], ['query']),
    'listLessons' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Vec(LessonSummary)],
        ['query'],
      ),
    'listRevisions' : IDL.Func([], [IDL.Vec(RevisionItem)], ['query']),
    'listSubjects' : IDL.Func([], [IDL.Vec(SubjectView)], ['query']),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'startExam' : IDL.Func([IDL.Nat], [ExamSession], []),
    'submitAnswer' : IDL.Func([IDL.Nat, IDL.Nat], [AnswerResult], []),
    'submitExam' : IDL.Func([IDL.Nat, IDL.Vec(ExamAnswer)], [ExamResult], []),
    'updateProfile' : IDL.Func([ProfileInput], [ProfileView], []),
  });
};

export const init = ({ IDL }) => { return []; };