/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface ActivityEntry {
    at: Timestamp;
    lessonId: LessonId;
    kind: string;
    detail: string;
}
export interface AiExplanation {
    question: string;
    answer: string;
    level: string;
}
export interface AnswerResult {
    correctIndex: bigint;
    explanation: string;
    correct: boolean;
}
export interface Badge {
    id: BadgeId;
    icon: string;
    name: string;
    description: string;
}
export type BadgeId = string;
export interface Cell {
    value: Value;
    name: string;
}
export interface CondensedPath {
    lessonId: LessonId;
    summary: string;
    steps: Array<LearningStep>;
    durationMinutes: DurationMinutes;
}
export type DurationMinutes = bigint;
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface ExamAnswer {
    exerciseId: ExerciseId;
    selectedIndex: bigint;
}
export type ExamId = bigint;
export interface ExamQuestion {
    exerciseId: ExerciseId;
    prompt: string;
    choices: Array<string>;
}
export interface ExamQuestionResult {
    exerciseId: ExerciseId;
    correctIndex: bigint;
    explanation: string;
    correct: boolean;
    selectedIndex: bigint;
    prompt: string;
}
export interface ExamResult {
    total: bigint;
    results: Array<ExamQuestionResult>;
    score: bigint;
    examId: ExamId;
    sessionId: SessionId;
}
export interface ExamSession {
    lessonId: LessonId;
    startedAt: Timestamp;
    submitted: boolean;
    durationSeconds: bigint;
    examId: ExamId;
    sessionId: SessionId;
}
export interface ExamView {
    id: ExamId;
    lessonId: LessonId;
    title: string;
    durationSeconds: bigint;
    questions: Array<ExamQuestion>;
}
export type ExerciseId = bigint;
export interface ExerciseView {
    id: ExerciseId;
    lessonId: LessonId;
    prompt: string;
    choices: Array<string>;
}
export interface LessonDetail {
    id: LessonId;
    curriculum: string;
    title: string;
    country: string;
    explanation: string;
    level: string;
    language: string;
    memorizationSummary: string;
    example: string;
    keyPoints: Array<string>;
    subjectId: SubjectId;
    memorizationPoints: Array<string>;
}
export type LessonId = bigint;
export interface LessonProgress {
    lessonId: LessonId;
    masteryRate: bigint;
    updatedAt: Timestamp;
    steps: Array<StepState>;
    currentStep: LearningStep;
}
export interface LessonSummary {
    id: LessonId;
    title: string;
    level: string;
    subjectId: SubjectId;
}
export interface ProfileInput {
    curriculum: string;
    country: string;
    level: string;
    language: string;
}
export interface ProfileView {
    curriculum: string;
    studentLevel: bigint;
    country: string;
    exercisesCompleted: bigint;
    level: string;
    language: string;
    updatedAt: Timestamp;
    lessonsCompleted: bigint;
    points: bigint;
}
export interface ProgressOverview {
    subjects: Array<SubjectMastery>;
    recentActivity: Array<ActivityEntry>;
    level: bigint;
    totalPoints: bigint;
}
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface RevisionItem {
    lessonId: LessonId;
    title: string;
    subjectId: SubjectId;
    priority: bigint;
    reason: string;
}
export interface RewardState {
    badges: Array<Badge>;
    level: bigint;
    points: bigint;
}
export type SessionId = bigint;
export interface StepState {
    step: LearningStep;
    completed: boolean;
}
export type SubjectId = bigint;
export interface SubjectMastery {
    masteryRate: bigint;
    name: string;
    subjectId: SubjectId;
}
export interface SubjectView {
    id: SubjectId;
    icon: string;
    name: string;
    description: string;
}
export type Timestamp = bigint;
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export enum LearningStep {
    entrainer = "entrainer",
    memoriser = "memoriser",
    comprendre = "comprendre",
    corriger = "corriger",
    exemple = "exemple",
    tester = "tester",
    maitriser = "maitriser"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    advanceStep(lessonId: bigint): Promise<LessonProgress>;
    askAiTeacher(lessonId: bigint, question: string): Promise<AiExplanation>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    execute(qJson: string): Promise<Result>;
    getApiDoc(): Promise<string>;
    getCallerUserRole(): Promise<UserRole>;
    getCondensedPath(lessonId: bigint, durationMinutes: bigint): Promise<CondensedPath>;
    getExam(lessonId: bigint): Promise<ExamView | null>;
    getLesson(lessonId: bigint): Promise<LessonDetail | null>;
    getLessonProgress(lessonId: bigint): Promise<LessonProgress | null>;
    getProfile(): Promise<ProfileView | null>;
    getProgress(): Promise<ProgressOverview>;
    getRewards(): Promise<RewardState>;
    isCallerAdmin(): Promise<boolean>;
    listExercises(lessonId: bigint): Promise<Array<ExerciseView>>;
    listLessons(subjectId: bigint, level: string): Promise<Array<LessonSummary>>;
    listRevisions(): Promise<Array<RevisionItem>>;
    listSubjects(): Promise<Array<SubjectView>>;
    schema(): Promise<string>;
    startExam(examId: bigint): Promise<ExamSession>;
    submitAnswer(exerciseId: bigint, selectedIndex: bigint): Promise<AnswerResult>;
    submitExam(sessionId: bigint, answers: Array<ExamAnswer>): Promise<ExamResult>;
    updateProfile(input: ProfileInput): Promise<ProfileView>;
}
import type { Cell as _Cell, CondensedPath as _CondensedPath, DurationMinutes as _DurationMinutes, Error as _Error, ExamView as _ExamView, LearningStep as _LearningStep, LessonDetail as _LessonDetail, LessonId as _LessonId, LessonProgress as _LessonProgress, ProfileView as _ProfileView, Result as _Result, Result__1 as _Result__1, StepState as _StepState, Timestamp as _Timestamp, UserRole as _UserRole, Value as _Value } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async advanceStep(arg0: bigint): Promise<LessonProgress> {
        if (this.processError) {
            try {
                const result = await this.actor.advanceStep(arg0);
                return from_candid_LessonProgress_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.advanceStep(arg0);
            return from_candid_LessonProgress_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async askAiTeacher(arg0: bigint, arg1: string): Promise<AiExplanation> {
        if (this.processError) {
            try {
                const result = await this.actor.askAiTeacher(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.askAiTeacher(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCondensedPath(arg0: bigint, arg1: bigint): Promise<CondensedPath> {
        if (this.processError) {
            try {
                const result = await this.actor.getCondensedPath(arg0, arg1);
                return from_candid_CondensedPath_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCondensedPath(arg0, arg1);
            return from_candid_CondensedPath_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExam(arg0: bigint): Promise<ExamView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getExam(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExam(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLesson(arg0: bigint): Promise<LessonDetail | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLesson(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLesson(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLessonProgress(arg0: bigint): Promise<LessonProgress | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLessonProgress(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLessonProgress(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(): Promise<ProfileView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProgress(): Promise<ProgressOverview> {
        if (this.processError) {
            try {
                const result = await this.actor.getProgress();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProgress();
            return result;
        }
    }
    async getRewards(): Promise<RewardState> {
        if (this.processError) {
            try {
                const result = await this.actor.getRewards();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRewards();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listExercises(arg0: bigint): Promise<Array<ExerciseView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listExercises(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listExercises(arg0);
            return result;
        }
    }
    async listLessons(arg0: bigint, arg1: string): Promise<Array<LessonSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.listLessons(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listLessons(arg0, arg1);
            return result;
        }
    }
    async listRevisions(): Promise<Array<RevisionItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.listRevisions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRevisions();
            return result;
        }
    }
    async listSubjects(): Promise<Array<SubjectView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSubjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSubjects();
            return result;
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async startExam(arg0: bigint): Promise<ExamSession> {
        if (this.processError) {
            try {
                const result = await this.actor.startExam(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startExam(arg0);
            return result;
        }
    }
    async submitAnswer(arg0: bigint, arg1: bigint): Promise<AnswerResult> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAnswer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAnswer(arg0, arg1);
            return result;
        }
    }
    async submitExam(arg0: bigint, arg1: Array<ExamAnswer>): Promise<ExamResult> {
        if (this.processError) {
            try {
                const result = await this.actor.submitExam(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitExam(arg0, arg1);
            return result;
        }
    }
    async updateProfile(arg0: ProfileInput): Promise<ProfileView> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0);
            return result;
        }
    }
}
function from_candid_Cell_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_CondensedPath_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CondensedPath): CondensedPath {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_LearningStep_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LearningStep): LearningStep {
    return "entrainer" in value ? LearningStep.entrainer : "memoriser" in value ? LearningStep.memoriser : "comprendre" in value ? LearningStep.comprendre : "corriger" in value ? LearningStep.corriger : "exemple" in value ? LearningStep.exemple : "tester" in value ? LearningStep.tester : "maitriser" in value ? LearningStep.maitriser : value;
}
function from_candid_LessonProgress_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LessonProgress): LessonProgress {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_StepState_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StepState): StepState {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_Value_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExamView]): ExamView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LessonDetail]): LessonDetail | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LessonProgress]): LessonProgress | null {
    return value.length === 0 ? null : from_candid_LessonProgress_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProfileView]): ProfileView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n14(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n18(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lessonId: _LessonId;
    summary: string;
    steps: Array<_LearningStep>;
    durationMinutes: _DurationMinutes;
}): {
    lessonId: LessonId;
    summary: string;
    steps: Array<LearningStep>;
    durationMinutes: DurationMinutes;
} {
    return {
        lessonId: value.lessonId,
        summary: value.summary,
        steps: from_candid_vec_n23(_uploadFile, _downloadFile, value.steps),
        durationMinutes: value.durationMinutes
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lessonId: _LessonId;
    masteryRate: bigint;
    updatedAt: _Timestamp;
    steps: Array<_StepState>;
    currentStep: _LearningStep;
}): {
    lessonId: LessonId;
    masteryRate: bigint;
    updatedAt: Timestamp;
    steps: Array<StepState>;
    currentStep: LearningStep;
} {
    return {
        lessonId: value.lessonId,
        masteryRate: value.masteryRate,
        updatedAt: value.updatedAt,
        steps: from_candid_vec_n7(_uploadFile, _downloadFile, value.steps),
        currentStep: from_candid_LearningStep_n10(_uploadFile, _downloadFile, value.currentStep)
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    step: _LearningStep;
    completed: boolean;
}): {
    step: LearningStep;
    completed: boolean;
} {
    return {
        step: from_candid_LearningStep_n10(_uploadFile, _downloadFile, value.step),
        completed: value.completed
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LearningStep>): Array<LearningStep> {
    return value.map((x)=>from_candid_LearningStep_n10(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StepState>): Array<StepState> {
    return value.map((x)=>from_candid_StepState_n8(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
